### ISSUE TITLE
Develop initial specifications for user-facing interface to analysis system components

### ISSUE THREAD

**Issue by BenGalewsky** [iris-hep/project-milestones#1]
We will develop a set of user stories that cover the end-to-end analysis process.

# Assumptions
1. Will be articulated as a set of user stories
2. Milestone does not include the work to solicit community feedback. Just an initial first draft.

# Acceptance Criteria
1. Set of user stories in [as-user-facing](https://github.com/iris-hep/as-user-facing) repo
2. Each story is written in the _As a < type of user >, I want < some goal > so that < some reason >_ format
3. Each story includes assumptions that underly the statement
4. Each story includes acceptance criteria for how we would know that the story has been implemented

**Comment by cranmer** [comment]
pyhf - @matthewfeickert could you please check if there is a good user story for the reinterpretation use case.

**Comment by alexander-held** [comment]
The [as-user-facing](https://github.com/iris-hep/as-user-facing) repository includes a description of template-fit-based statistical analysis.

`template-fit.md` provides the high level picture.

### Event selection
Template distributions are built via specified *cuts*, instructions of requirements set on events for them to be part of the distributions. These selection criteria need to be specified ,and the user story `sepecify_selection_criteria.md` summarizes the specification aspect. In a second step, the selection criteria need to also be applied to data in order to obtain the relevant distributions, this aspect of the workflow is summarized in the user story `apply_selection_criteria.md`.  Both of the user stories satisfy the acceptance criteria described above.

### Template fit visualization
The visualization of various aspects of template fits is described in a set of user stories, starting with a high level description in `fit-visualization.md`.  All subsequent user stories also satisfy the above mentioned acceptance criteria. Besides the user story aspect, they also include example implementations for reference.

#### Inputs to the fit
The user story in `fit-visualization/nuisance-parameter-effects.md` describes the visualization of the template distributions showing the effects of nuisance parameters. `fit-visualization/pruning-plot.md` describes an overview showing how certain nuisance parameters modify distributions in the fit.

#### Fit results
The user stories `fit-visualization/exclusion-limits.md` and `fit-visualization/likelihood-scan-and-contours.md` are dedicated to standard ways of visualizing fit results, which are commonly found in publications. These are exclusion limits (including the "brazil band plots"), likelihood scans and confidence level contours.

Additional relevant supporting information providing further details about the statistical analysis include correlation matrices, with a user story in `fit-visualization/correlation-matrix.md`. The so-called "ranking plot" is summarized in the user story `fit-visualization/ranking-plot.md`, it highlights the most important nuisance parameters and their effects on the signal extraction. Lastly, the so-called "pull plots" are described in user story `fit-visualization/pull-plot.md`, they are an important way to summarize fit results for nuisance parameters.
